// Pack the composed skill-icon tiles into ONE sprite sheet + index module,
// mirroring the game's existing monster/boss sheets. Emits:
//   src/assets/skillIconsAtlas.js
//     export const SKILL_ICON_COLS  = <cols>
//     export const SKILL_ICON_TS    = <cell px>
//     export const SKILL_ICON_INDEX = { 'sk_wa_whirl': 0, 'sk_w_immortal@ks': 1, ... }
//     export const SKILL_ICON_ATLAS = 'data:image/png;base64,...'
//
// Keys ending in '@ks' are the octagon (keystone) variants.
//
// Usage: node tools/skill-icons/pack.mjs [tilesDir]
import { chromium } from 'playwright';
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import { launchChromium } from './pw.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const WORK = process.env.SKILL_ICON_WORKDIR || resolve(HERE, '.work');
const TILE_DIR = process.argv[2] ? resolve(process.argv[2]) : join(WORK, 'tiles');
const OUT = resolve(HERE, '../../src/assets/skillIconsAtlas.js');

const COLS = 16;
const TS = 96;   // per-cell px in the packed sheet (art shows at <=64px in game)

function main() {
  if (!existsSync(TILE_DIR)) { console.error(`no tiles dir: ${TILE_DIR}`); process.exit(2); }
  const files = readdirSync(TILE_DIR).filter((f) => f.endsWith('.png')).sort();
  if (!files.length) { console.error('no tiles to pack'); process.exit(2); }
  const keys = files.map((f) => f.replace(/\.png$/, ''));
  const rows = Math.ceil(keys.length / COLS);
  console.log(`Packing ${keys.length} tiles -> ${COLS}x${rows} sheet @ ${TS}px`);
  return { files, keys, rows };
}

const { files, keys, rows } = main();

const browser = await launchChromium(chromium);
const page = await browser.newPage();
await page.setContent('<!doctype html><meta charset=utf8><canvas id=c></canvas>');
const tiles = files.map((f) => 'data:image/png;base64,' + readFileSync(join(TILE_DIR, f)).toString('base64'));

const dataUrl = await page.evaluate(async ({ tiles, cols, rows, ts }) => {
  const cv = document.getElementById('c');
  cv.width = cols * ts; cv.height = rows * ts;
  const ctx = cv.getContext('2d');
  ctx.imageSmoothingEnabled = true; ctx.imageSmoothingQuality = 'high';
  for (let i = 0; i < tiles.length; i++) {
    const img = new Image();
    await new Promise((res, rej) => { img.onload = res; img.onerror = rej; img.src = tiles[i]; });
    const col = i % cols, row = (i / cols) | 0;
    ctx.drawImage(img, col * ts, row * ts, ts, ts);
  }
  return cv.toDataURL('image/png');
}, { tiles, cols: COLS, rows, ts: TS });
await browser.close();

const index = {};
keys.forEach((k, i) => { index[k] = i; });

const body = `// AUTO-GENERATED by tools/skill-icons/pack.mjs — do not edit by hand.
// One packed sheet of class-themed skill-icon badges (${keys.length} cells,
// ${COLS} cols x ${rows} rows, ${TS}px each). Keys ending in '@ks' are the
// octagon keystone variants. Regenerate with:
//   node tools/skill-icons/generate.mjs --all   # produces the tiles
//   node tools/skill-icons/pack.mjs             # packs this module
export const SKILL_ICON_COLS = ${COLS};
export const SKILL_ICON_ROWS = ${rows};
export const SKILL_ICON_TS = ${TS};
export const SKILL_ICON_INDEX = ${JSON.stringify(index)};
export const SKILL_ICON_ATLAS = '${dataUrl}';
`;
writeFileSync(OUT, body);
const kb = (Buffer.byteLength(body) / 1024) | 0;
console.log(`Wrote ${OUT} (${kb} KB, ${keys.length} icons)`);
